import express from "express";
const router = express.Router();
import { ajouterUtilisateur, listerUtilisateurs, getUtilisateurById, updateUtilisateur, deleteUtilisateur } from "../controllers/userController.js";
import protect from "../middlewares/authMiddleware.js";
import authorize from "../middlewares/roleMiddleware.js";
import upload from "../middlewares/upload.js";
router.post("/ajouter", upload.single("avatar"), ajouterUtilisateur);
router.get("/list", protect, authorize(["admin","teacher"]), listerUtilisateurs);
router.get("/:id", getUtilisateurById);
router.put("/:id", upload.single("avatar"), updateUtilisateur);
router.delete("/:id", deleteUtilisateur);
export default router;