const express =require("express");
const cors = require("cors");
const dotenv = require("dotenv");
const connectDB = require("./config/db.js");
const path = require("path");
dotenv.config();
const app = express();
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({extended : true}));
connectDB();
app.use("/uploads", express.static(path.join(path.resolve(), "/uploads")));
app.use("/api/auth", require("./routes/authRoutes"));
app.use("/api/users",require("./routes/userRoutes.js"));
app.use("/api/courses",require("./routes/courseRoutes.js"));
app.use("/api/departements",require("./routes/departementRoutes.js"));
app.use("/api/quizzes",require("./routes/quizRoutes.js"));
app.use("/api/quizattempts", require("./routes/quizAttemptRoutes.js"));
app.use("/api/answers", require("./routes/answerRoutes.js"));
app.use("/api/questions", require("./routes/questionRoutes.js"));
app.use("/api/choices", require("./routes/choiceRoutes.js"));
app.use("/api/auditlogs", require("./routes/auditLogRoutes.js"));
app.use("/api/modules", require("./routes/moduleRoutes.js"));
app.use("/api/lessons", require("./routes/lessonRoutes.js"));
app.use("/api/notifications", require("./routes/notificationRoutes.js"));
app.use("/api/recommendations", require("./routes/recommendationRoutes.js"));
app.use("/api/inscriptions", require("./routes/inscriptionRoutes.js"));
app.use("/api/performancemetrics", require("./routes/performanceMetricRoutes.js"));
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
    console.log(`Server lancé sur http://localhost:${PORT}`);
});