import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import path from "path";
import connectDB from "./config/db.js";
import adminRoutes from "./routes/adminRoutes.js";
import authRoutes from "./routes/authRoutes.js";
import userRoutes from "./routes/userRoutes.js";
import courseRoutes from "./routes/courseRoutes.js";
import departementRoutes from "./routes/departementRoutes.js";
import quizRoutes from "./routes/quizRoutes.js";
import quizAttemptRoutes from "./routes/quizAttemptRoutes.js";
import answerRoutes from "./routes/answerRoutes.js";
import questionRoutes from "./routes/questionRoutes.js";
import choiceRoutes from "./routes/choiceRoutes.js";
import auditLogRoutes from "./routes/auditLogRoutes.js";
import moduleRoutes from "./routes/moduleRoutes.js";
import lessonRoutes from "./routes/lessonRoutes.js";
import notificationRoutes from "./routes/notificationRoutes.js";
import recommendationRoutes from "./routes/recommendationRoutes.js";
import inscriptionRoutes from "./routes/inscriptionRoutes.js";
import performanceMetricRoutes from "./routes/performanceMetricRoutes.js";
import statisticsRoutes from "./routes/statisticsRoutes.js";
dotenv.config();
const app = express();
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
connectDB();
app.use('/api/statistics', statisticsRoutes);
app.use("/admin", adminRoutes);
app.use("/uploads", express.static(path.join(path.resolve(), "/uploads")));
app.use("/api/auth", authRoutes);
app.use("/api/users", userRoutes);
app.use("/api/courses", courseRoutes);
app.use("/api/departements", departementRoutes);
app.use("/api/quizzes", quizRoutes);
app.use("/api/quizattempts", quizAttemptRoutes);
app.use("/api/answers", answerRoutes);
app.use("/api/questions", questionRoutes);
app.use("/api/choices", choiceRoutes);
app.use("/api/auditlogs", auditLogRoutes);
app.use("/api/modules", moduleRoutes);
app.use("/api/lessons", lessonRoutes);
app.use("/api/notifications", notificationRoutes);
app.use("/api/recommendations", recommendationRoutes);
app.use("/api/inscriptions", inscriptionRoutes);
app.use("/api/performancemetrics", performanceMetricRoutes);
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
    console.log(`Server lancé sur http://localhost:${PORT}`);
});